title: Project Connecticut
description: A ComputerCraft Server
theme: just-the-docs

url: https://docs.ct.knijn.one

#aux_links:
#  Template Repository: https://github.com/just-the-docs/just-the-docs-template
